name: Lint

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  checks: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install eslint
        run: npm install eslint eslint-plugin-react@latest @typescript-eslint/eslint-plugin eslint-config-next
      - name: Install tsc
        run: npm install typescript
      - name: Install prettier
        run: npm install prettier

      - name: Run linters
        # https://github.com/marketplace/actions/lint-action
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: kanban-dashboard/src
          eslint_extensions: js,tsx,ts
          prettier: true
          prettier_dir: kanban-dashboard/src
          tsc: true
          tsc_dir: kanban-dashboard/src
