name: Prettier
on:
  push:
    branches: '**'

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{mjs,mts,jsx,tsx,md,ts,js}
          only_changed: True
          github_token: ${{ secrets.GITHUB_TOKEN }}
