name: Update DB UML Diagram

on:
  push:
    paths:
      - kanban-dashboard/prisma/schema.prisma
      - kanban-dashboard/prisma/README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prisma-uml
        run: npm install prisma-uml

      - name: Run prisma-uml
        run: npx prisma-uml kanban-dashboard/prisma/schema.prisma -o png -f kanban-dashboard/prisma/uml.png

      - uses: EndBug/add-and-commit@v9
        with:
          add: kanban-dashboard/prisma/uml.png
          default_author: github_actions
          message: Update DB UML Diagram
